#include "../include/path_countries.h"

char	*etats[] = {
		"Afghanistan",
		"Afrique du Sud",
		"Albanie",
		"Algerie",
		"Allemagne", 
		"Andorre",
		"Angola",
		"Arabie Saoudite",
		"Argentine",
		"Armenie",
		"Autriche",
		"Azerbaidjan",
		"Bahrein",
		"Bangladesh",
		"Belgique",
		"Benin",
		"Bhoutan",
		"Bielorussie",
		"Birmanie",
		"Bolivie",
		"Bosnie Herzegovine",
		"Botswana",
		"Bresil",
		"Brunei",
		"Bulgarie",
		"Burkina Faso",
		"Burundi",
		"Cambodge",
		"Cameroun",
		"Canada",
		"Chili",
		"Chine",
		"Colombie",
		"Republique du Congo",
		"Coree du Nord",
		"Coree du Sud",
		"Costa Rica",
		"Cote d'Ivoire",
		"Croatie",
		"Danemark",
		"Djibouti",
		"Egypte",
		"Emirats Arabes Unis",
		"Equateur",
		"Erythree",
		"Espagne",
		"Estonie",
		"Eswatini",
		"Etats Unis",
		"Ethiopie",
		"Finlande",
		"France",
		"Gabon",
		"Gambie",
		"Georgie",
		"Ghana",
		"Grece",
		"Guatemala",
		"Guinee",
		"Guinee Equatoriale",
		"Guinee Bissau",
		"Guyana",
		"Honduras",
		"Hongrie",
		"Inde",
		"Indonesie",
		"Irak",
		"Iran",
		"Palestine",
		"Italie",
		"Jordanie",
		"Kazakhstan",
		"Kenya",
		"Kirghizistan",
		"Kosovo",
		"Koweit",
		"Laos",
		"Lesotho",
		"Lettonie",
		"Liban",
		"Liberia",
		"Libye",
		"Liechtenstein",
		"Lituanie",
		"Luxembourg",
		"Macedoine",
		"Malaisie",
		"Malawi",
		"Mali",
		"Maroc",
		"Mauritanie",
		"Mexique",
		"Moldavie",
		"Monaco",
		"Mongolie",
		"Montenegro",
		"Mozambique",
		"Namibie",
		"Nepal",
		"Nicaragua",
		"Niger",
		"Nigeria",
		"Norvege",
		"Oman",
		"Ouganda",
		"Ouzbekistan",
		"Pakistan",
		"Panama",
		"Papouasie",
		"Paraguay",
		"Pays Bas",
		"Perou",
		"Pologne",
		"Portugal",
		"Qatar",
		"Republique Centrafricaine",
		"Republique Democratique du Congo",
		"Tchequie",
		"Roumanie",
		"Russie",
		"Rwanda",
		"Saint Marin",
		"Salvador",
		"Senegal",
		"Serbie",
		"Sierra Leone",
		"Singapour",
		"Slovaquie",
		"Slovenie",
		"Somalie",
		"Soudan",
		"Soudan du Sude",
		"Suede",
		"Suisse",
		"Suriname",
		"Syrie",
		"Tadjikistan",
		"Tanzanie",
		"Tchad",
		"Thailande",
		"Togo",
		"Tunisie",
		"Turkmenistan",
		"Turquie",
		"Ukraine",
		"Uruguay",
		"Vatican",
		"Venezuela",
		"Vietnam",
		"Yemen",
		"Zambie",
		"Zimbabwe"
	};

void	random_itineraire(char **depart, char **arrivee)
{
	*depart = upcase(etats[rand() % 152]);
	*arrivee = upcase(etats[rand() % 152]);

	while (!strcmp(*depart, *arrivee))
	{
		*depart = upcase(etats[rand() % 152]);
		*arrivee = upcase(etats[rand() % 152]);
	}
}