#include "../include/path_countries.h"

t_pays	afghanistan, afrique_du_sud, albanie, algerie, allemagne, andorre,
	angola, arabie_saoudite, argentine, armenie, autriche, azerbaidjan, 
	bahrein, bangladesh, belgique, belize, benin, bhoutan, bielorussie, birmanie,
	bolivie, bosnie, botswana, bresil, brunei, bulgarie, burkina_faso,
	burundi, cambodge, cameroun, canada, chili, chine, colombie,
	republique_du_congo, coree_du_nord, coree_du_sud, costa_rica,
	cote_ivoire, croatie, danemark, djibouti, egypte, emirats_arabes_unis,
	equateur, erythree, espagne, estonie, eswatini, etats_unis, ethiopie,
	finlande, france, gabon, gambie, georgie, ghana, grece, guatemala,
	guinee, guinee_equatoriale, guinee_bissau, guyana, honduras, hongrie,
	inde, indonesie, irak, iran, palestine, italie, jordanie, kazakhstan,
	kenya, kirghizistan, kosovo, koweit, laos, lesotho, lettonie, liban,
	liberia, libye, liechtenstein, lituanie, luxembourg, macedoine,
	malaisie, malawi, mali, maroc, mauritanie, mexique, moldavie, monaco,
	mongolie, montenegro, mozambique, namibie, nepal, nicaragua, niger,
	nigeria, norvege, oman, ouganda, ouzbekistan, pakistan, panama,
	papouasie, paraguay, pays_bas, perou, pologne, portugal, qatar,
	republique_centrafrique, republique_democratique_du_congo, tchequie,
	roumanie, russie, rwanda, saint_marin, salvador, senegal, serbie,
	sierra_leone, singapour, slovaquie, slovenie, somalie, soudan,
	soudan_du_sud, suede, suisse, suriname, syrie, tadjikistan, tanzanie,
	tchad, thailande, togo, tunisie, turkmenistan, turquie, ukraine,
	uruguay, vatican, venezuela, vietnam, yemen, zambie, zimbabwe;

int	main(void)
{
	char	*depart;
	char	*arrivee;
	t_pays	*actuel;

	srand(time(NULL));
	random_itineraire(&depart, &arrivee);
	init_pays();
	t_pays *countries[] = {
		&afghanistan, &afrique_du_sud, &albanie, &algerie, &allemagne, &andorre,
		&angola, &arabie_saoudite, &argentine, &armenie, &autriche, &azerbaidjan, 
		&bahrein, &bangladesh, &belgique, &belize, &benin, &bhoutan, &bielorussie, &birmanie,
		&bolivie, &bosnie, &botswana, &bresil, &brunei, &bulgarie, &burkina_faso,
		&burundi, &cambodge, &cameroun, &canada, &chili, &chine, &colombie,
		&republique_du_congo, &coree_du_nord, &coree_du_sud, &costa_rica,
		&cote_ivoire, &croatie, &danemark, &djibouti, &egypte, &emirats_arabes_unis,
		&equateur, &erythree, &espagne, &estonie, &eswatini, &etats_unis, &ethiopie,
		&finlande, &france, &gabon, &gambie, &georgie, &ghana, &grece, &guatemala,
		&guinee, &guinee_equatoriale, &guinee_bissau, &guyana, &honduras, &hongrie,
		&inde, &indonesie, &irak, &iran, &palestine, &italie, &jordanie, &kazakhstan,
		&kenya, &kirghizistan, &kosovo, &koweit, &laos, &lesotho, &lettonie, &liban,
		&liberia, &libye, &liechtenstein, &lituanie, &luxembourg, &macedoine,
		&malaisie, &malawi, &mali, &maroc, &mauritanie, &mexique, &moldavie, &monaco,
		&mongolie, &montenegro, &mozambique, &namibie, &nepal, &nicaragua, &niger,
		&nigeria, &norvege, &oman, &ouganda, &ouzbekistan, &pakistan, &panama,
		&papouasie, &paraguay, &pays_bas, &perou, &pologne, &portugal, &qatar,
		&republique_centrafrique, &republique_democratique_du_congo, &tchequie,
		&roumanie, &russie, &rwanda, &saint_marin, &salvador, &senegal, &serbie,
		&sierra_leone, &singapour, &slovaquie, &slovenie, &somalie, &soudan,
		&soudan_du_sud, &suede, &suisse, &suriname, &syrie, &tadjikistan, &tanzanie,
		&tchad, &thailande, &togo, &tunisie, &turkmenistan, &turquie, &ukraine,
		&uruguay, &vatican, &venezuela, &vietnam, &yemen, &zambie, &zimbabwe
	};
	actuel = get_country(depart, *countries);
	init_distance(arrivee, countries);
	game(depart, arrivee, actuel);
	bot(countries, depart);
	free(depart);
	free(arrivee);
	return (0);
}

void	init_pays(void)
{
	all_zero(&afghanistan);
	afghanistan.noms[0] = "AFGHANISTAN";
	afghanistan.frontieres[0] = &turkmenistan;
	afghanistan.frontieres[1] = &tadjikistan;
	afghanistan.frontieres[2] = &pakistan;
	afghanistan.frontieres[3] = &iran;
	afghanistan.frontieres[4] = &chine;
	afghanistan.frontieres[5] = &ouzbekistan;
	all_zero(&afrique_du_sud);
	afrique_du_sud.noms[0] = "AFRIQUE DU SUD";
	afrique_du_sud.frontieres[0] = &namibie;
	afrique_du_sud.frontieres[1] = &botswana;
	afrique_du_sud.frontieres[2] = &zimbabwe;
	afrique_du_sud.frontieres[3] = &mozambique;
	afrique_du_sud.frontieres[4] = &lesotho;
	afrique_du_sud.frontieres[5] = &eswatini;
	all_zero(&albanie);
	albanie.noms[0] = "ALBANIE";
	albanie.frontieres[0] = &montenegro;
	albanie.frontieres[1] = &kosovo;
	albanie.frontieres[2] = &macedoine;
	albanie.frontieres[3] = &grece;
	all_zero(&algerie);
	algerie.noms[0] = "ALGERIE";
	algerie.frontieres[0] = &maroc;
	algerie.frontieres[1] = &mauritanie;
	algerie.frontieres[2] = &mali;
	algerie.frontieres[3] = &niger;
	algerie.frontieres[4] = &libye;
	algerie.frontieres[5] = &tunisie;
	all_zero(&allemagne);
	allemagne.noms[0] = "ALLEMAGNE";
	allemagne.frontieres[0] = &pays_bas;
	allemagne.frontieres[1] = &belgique;
	allemagne.frontieres[2] = &luxembourg;
	allemagne.frontieres[3] = &france;
	allemagne.frontieres[4] = &suisse;
	allemagne.frontieres[5] = &autriche;
	allemagne.frontieres[6] = &tchequie;
	allemagne.frontieres[7] = &pologne;
	allemagne.frontieres[8] = &danemark;
	all_zero(&andorre);
	andorre.noms[0] = "ANDORRE";
	andorre.frontieres[0] = &france;
	andorre.frontieres[1] = &espagne;
	all_zero(&angola);
	angola.noms[0] = "ANGOLA";
	angola.frontieres[0] = &republique_democratique_du_congo;
	angola.frontieres[1] = &zambie;
	angola.frontieres[2] = &namibie;
	all_zero(&arabie_saoudite);
	arabie_saoudite.noms[0] = "ARABIE SAOUDITE";
	arabie_saoudite.frontieres[0] = &jordanie;
	arabie_saoudite.frontieres[1] = &irak;
	arabie_saoudite.frontieres[2] = &bahrein;
	arabie_saoudite.frontieres[3] = &koweit;
	arabie_saoudite.frontieres[4] = &qatar;
	arabie_saoudite.frontieres[5] = &emirats_arabes_unis;
	arabie_saoudite.frontieres[6] = &oman;
	arabie_saoudite.frontieres[7] = &yemen;
	all_zero(&argentine);
	argentine.noms[0] = "ARGENTINE";
	argentine.frontieres[0] = &chili;
	argentine.frontieres[1] = &bolivie;
	argentine.frontieres[2] = &paraguay;
	argentine.frontieres[3] = &uruguay;
	argentine.frontieres[4] = &bresil;
	all_zero(&armenie);
	armenie.noms[0] = "ARMENIE";
	armenie.frontieres[0] = &turquie;
	armenie.frontieres[1] = &georgie;
	armenie.frontieres[2] = &iran;
	armenie.frontieres[3] = &azerbaidjan;
	all_zero(&autriche);
	autriche.noms[0] = "AUTRICHE";
	autriche.frontieres[0] = &allemagne;
	autriche.frontieres[1] = &tchequie;
	autriche.frontieres[2] = &slovaquie;
	autriche.frontieres[3] = &hongrie;
	autriche.frontieres[4] = &slovenie;
	autriche.frontieres[5] = &italie;
	autriche.frontieres[6] = &suisse;
	autriche.frontieres[7] = &liechtenstein;
	all_zero(&azerbaidjan);
	azerbaidjan.noms[0] = "AZERBAIDJAN";
	azerbaidjan.frontieres[0] = &armenie;
	azerbaidjan.frontieres[1] = &iran;
	azerbaidjan.frontieres[2] = &russie;
	azerbaidjan.frontieres[3] = &georgie;
	all_zero(&bahrein);
	bahrein.noms[0] = "BAHREIN";
	bahrein.frontieres[0] = &arabie_saoudite;
	all_zero(&bangladesh);
	bangladesh.noms[0] = "BANGLADESH";
	bangladesh.frontieres[0] = &inde;
	bangladesh.frontieres[1] = &birmanie;
	all_zero(&belgique);
	belgique.noms[0] = "BELGIQUE";
	belgique.frontieres[0] = &pays_bas;
	belgique.frontieres[1] = &france;
	belgique.frontieres[2] = &allemagne;
	belgique.frontieres[3] = &luxembourg;
	all_zero(&benin);
	benin.noms[0] = "BENIN";
	benin.frontieres[0] = &togo;
	benin.frontieres[1] = &burkina_faso;
	benin.frontieres[2] = &niger;
	benin.frontieres[3] = &nigeria;
	all_zero(&belize);
	belize.noms[0] = "BELIZE";
	belize.frontieres[0] = &mexique;
	belize.frontieres[1] = &guatemala;
	all_zero(&bhoutan);
	bhoutan.noms[0] = "BHOUTAN";
	bhoutan.frontieres[0] = &inde;
	bhoutan.frontieres[1] = &chine;
	all_zero(&bielorussie);
	bielorussie.noms[0] = "BIELORUSSIE";
	bielorussie.noms[1] = "BELARUS";
	bielorussie.frontieres[0] = &pologne;
	bielorussie.frontieres[1] = &lituanie;
	bielorussie.frontieres[2] = &lettonie;
	bielorussie.frontieres[3] = &russie;
	bielorussie.frontieres[4] = &ukraine;
	all_zero(&birmanie);
	birmanie.noms[0] = "BIRMANIE";
	birmanie.noms[1] = "MYANMAR";
	birmanie.frontieres[0] = &inde;
	birmanie.frontieres[1] = &chine;
	birmanie.frontieres[2] = &laos;
	birmanie.frontieres[3] = &thailande;
	birmanie.frontieres[4] = &bangladesh;
	all_zero(&bolivie);
	bolivie.noms[0] = "BOLIVIE";
	bolivie.frontieres[0] = &perou;
	bolivie.frontieres[1] = &bresil;
	bolivie.frontieres[2] = &chili;
	bolivie.frontieres[3] = &argentine;
	bolivie.frontieres[4] = &paraguay;
	all_zero(&bosnie);
	bosnie.noms[0] = "BOSNIE HERZEGOVINE";
	bosnie.noms[1] = "BOSNIE";
	bosnie.frontieres[0] = &croatie,
	bosnie.frontieres[1] = &serbie;
	bosnie.frontieres[2] = &montenegro;
	all_zero(&botswana);
	botswana.noms[0] = "BOTSWANA";
	botswana.frontieres[0] = &namibie;
	botswana.frontieres[1] = &afrique_du_sud;
	botswana.frontieres[2] = &zimbabwe;
	botswana.frontieres[3] = &zambie;
	all_zero(&bresil);
	bresil.noms[0] = "BRESIL";
	bresil.frontieres[0] = &france;
	bresil.frontieres[1] = &suriname;
	bresil.frontieres[2] = &guyana;
	bresil.frontieres[3] = &venezuela;
	bresil.frontieres[4] = &colombie;
	bresil.frontieres[5] = &perou;
	bresil.frontieres[6] = &bolivie;
	bresil.frontieres[7] = &paraguay;
	bresil.frontieres[8] = &argentine;
	bresil.frontieres[9] = &uruguay;
	all_zero(&brunei);
	brunei.noms[0] = "BRUNEI";
	brunei.noms[1] = "BRUNEI DARUSSALAM";
	brunei.frontieres[0] = &malaisie;
	all_zero(&bulgarie);
	bulgarie.noms[0] = "BULGARIE";
	bulgarie.frontieres[0] = &serbie;
	bulgarie.frontieres[1] = &roumanie;
	bulgarie.frontieres[2] = &macedoine;
	bulgarie.frontieres[3] = &grece;
	bulgarie.frontieres[4] = &turquie;
	all_zero(&burkina_faso);
	burkina_faso.noms[0] = "BURKINA FASO";
	burkina_faso.frontieres[0] = &mali;
	burkina_faso.frontieres[1] = &cote_ivoire;
	burkina_faso.frontieres[2] = &ghana;
	burkina_faso.frontieres[3] = &togo;
	burkina_faso.frontieres[4] = &benin;
	burkina_faso.frontieres[5] = &niger;
	all_zero(&burundi);
	burundi.noms[0] = "BURUNDI";
	burundi.frontieres[0] = &rwanda;
	burundi.frontieres[1] = &republique_democratique_du_congo;
	burundi.frontieres[2] = &tanzanie;
	all_zero(&cambodge);
	cambodge.noms[0] = "CAMBODGE";
	cambodge.frontieres[0] = &thailande;
	cambodge.frontieres[1] = &laos;
	cambodge.frontieres[2] = &vietnam;
	all_zero(&cameroun);
	cameroun.noms[0] = "CAMEROUN";
	cameroun.frontieres[0] = &nigeria;
	cameroun.frontieres[1] = &tchad;
	cameroun.frontieres[2] = &republique_centrafrique;
	cameroun.frontieres[3] = &republique_du_congo;
	cameroun.frontieres[4] = &gabon;
	cameroun.frontieres[5] = &guinee_equatoriale;
	all_zero(&canada);
	canada.noms[0] = "CANADA";
	canada.frontieres[0] = &etats_unis;
	all_zero(&chili);
	chili.noms[0] = "CHILI";
	chili.frontieres[0] = &perou;
	chili.frontieres[1] = &bolivie;
	chili.frontieres[2] = &argentine;
	all_zero(&chine);
	chine.noms[0] = "CHINE";
	chine.frontieres[0] = &russie;
	chine.frontieres[1] = &mongolie;
	chine.frontieres[2] = &kazakhstan;
	chine.frontieres[3] = &kirghizistan;
	chine.frontieres[4] = &tadjikistan;
	chine.frontieres[5] = &afghanistan;
	chine.frontieres[6] = &pakistan;
	chine.frontieres[7] = &inde;
	chine.frontieres[8] = &nepal;
	chine.frontieres[9] = &bhoutan;
	chine.frontieres[10] = &birmanie;
	chine.frontieres[11] = &laos;
	chine.frontieres[12] = &vietnam;
	chine.frontieres[13] = &coree_du_nord;
	all_zero(&colombie);
	colombie.noms[0] = "COLOMBIE";
	colombie.frontieres[0] = &panama;
	colombie.frontieres[1] = &equateur;
	colombie.frontieres[2] = &perou;
	colombie.frontieres[3] = &bresil;
	colombie.frontieres[4] = &venezuela;
	all_zero(&republique_du_congo);
	republique_du_congo.noms[0] = "REPUBLIQUE DU CONGO";
	republique_du_congo.noms[1] = "CONGO BRAZZAVILLE";
	republique_du_congo.frontieres[0] = &gabon;
	republique_du_congo.frontieres[1] = &cameroun;
	republique_du_congo.frontieres[2] = &republique_centrafrique;
	republique_du_congo.frontieres[3] = &republique_democratique_du_congo;
	republique_du_congo.frontieres[4] = &angola;
	all_zero(&coree_du_nord);
	coree_du_nord.noms[0] = "COREE DU NORD";
	coree_du_nord.frontieres[0] = &coree_du_sud;
	coree_du_nord.frontieres[1] = &chine;
	all_zero(&coree_du_sud);
	coree_du_sud.noms[0] = "COREE DU SUD";
	coree_du_sud.frontieres[0] = &coree_du_nord;
	all_zero(&costa_rica);
	costa_rica.noms[0] = "COSTA RICA";
	costa_rica.frontieres[0] = &nicaragua;
	costa_rica.frontieres[1] = &panama;
	all_zero(&cote_ivoire);
	cote_ivoire.noms[0] = "COTE D'IVOIRE";
	cote_ivoire.frontieres[0] = &liberia;
	cote_ivoire.frontieres[1] = &guinee;
	cote_ivoire.frontieres[2] = &mali;
	cote_ivoire.frontieres[3] = &burkina_faso;
	cote_ivoire.frontieres[4] = &ghana;
	all_zero(&croatie);
	croatie.noms[0] = "CROATIE";
	croatie.frontieres[0] = &slovenie;
	croatie.frontieres[1] = &bosnie;
	croatie.frontieres[2] = &serbie;
	croatie.frontieres[3] = &hongrie;
	all_zero(&danemark);
	danemark.noms[0] = "DANEMARK";
	danemark.frontieres[0] = &allemagne;
	danemark.frontieres[1] = &suede;
	all_zero(&djibouti);
	djibouti.noms[0] = "DJIBOUTI";
	djibouti.frontieres[0] = &erythree;
	djibouti.frontieres[1] = &ethiopie;
	djibouti.frontieres[2] = &somalie;
	all_zero(&egypte);
	egypte.noms[0] = "EGYPTE";
	egypte.frontieres[0] = &libye;
	egypte.frontieres[1] = &soudan;
	egypte.frontieres[2] = &palestine;
	all_zero(&emirats_arabes_unis);
	emirats_arabes_unis.noms[0] = "EMIRATS ARABES UNIS";
	emirats_arabes_unis.noms[1] = "EAU";
	emirats_arabes_unis.frontieres[0]= &arabie_saoudite;
	emirats_arabes_unis.frontieres[1] = &oman;
	all_zero(&equateur);
	equateur.noms[0] = "EQUATEUR";
	equateur.frontieres[0] = &colombie;
	equateur.frontieres[1] = &perou;
	all_zero(&erythree);
	erythree.noms[0] = "ERYTHREE";
	erythree.frontieres[0] = &soudan;
	erythree.frontieres[1] = &ethiopie;
	erythree.frontieres[2] = &djibouti;
	all_zero(&espagne);
	espagne.noms[0] = "ESPAGNE";
	espagne.frontieres[0] = &portugal;
	espagne.frontieres[1] = &france;
	espagne.frontieres[2] = &andorre;
	all_zero(&estonie);
	estonie.noms[0] = "ESTONIE";
	estonie.frontieres[0] = &russie;
	estonie.frontieres[1] = &lettonie;
	all_zero(&eswatini);
	eswatini.noms[0] = "ESWATINI";
	eswatini.frontieres[0] = &afrique_du_sud;
	eswatini.frontieres[1] = &mozambique;
	all_zero(&etats_unis);
	etats_unis.noms[0] = "USA";
	etats_unis.noms[1] = "ETATS UNIS";
	etats_unis.frontieres[0] = &canada;
	etats_unis.frontieres[1] = &mexique;
	all_zero(&ethiopie);
	ethiopie.noms[0] = "ETHIOPIE";
	ethiopie.frontieres[0] = &soudan;
	ethiopie.frontieres[1] = &soudan_du_sud;
	ethiopie.frontieres[2] = &kenya;
	ethiopie.frontieres[3] = &somalie;
	ethiopie.frontieres[4] = &djibouti;
	ethiopie.frontieres[5] = &erythree;
	all_zero(&finlande);
	finlande.noms[0] = "FINLANDE";
	finlande.frontieres[0] = &norvege;
	finlande.frontieres[1] = &suede;
	finlande.frontieres[2] = &russie;
	all_zero(&france);
	france.noms[0] = "FRANCE";
	france.frontieres[0] = &belgique;
	france.frontieres[1] = &allemagne;
	france.frontieres[2] = &suisse;
	france.frontieres[3] = &luxembourg;
	france.frontieres[4] = &italie;
	france.frontieres[5] = &andorre;
	france.frontieres[6] = &espagne;
	france.frontieres[7] = &bresil;
	france.frontieres[8] = &monaco;
	all_zero(&gabon);
	gabon.noms[0] = "GABON";
	gabon.frontieres[0] = &guinee_equatoriale;
	gabon.frontieres[1] = &cameroun;
	gabon.frontieres[2] = &republique_du_congo;
	all_zero(&gambie);
	gambie.noms[0] = "GAMBIE";
	gambie.frontieres[0] = &senegal;
	all_zero(&georgie);
	georgie.noms[0] = "GEORGIE";
	georgie.frontieres[0] = &russie;
	georgie.frontieres[1] = &armenie;
	georgie.frontieres[2] = &azerbaidjan;
	georgie.frontieres[3] = &turquie;
	all_zero(&ghana);
	ghana.noms[0] = "GHANA";
	ghana.frontieres[0] = &cote_ivoire;
	ghana.frontieres[1] = &burkina_faso;
	ghana.frontieres[2] = &togo;
	all_zero(&grece);
	grece.noms[0] = "GRECE";
	grece.frontieres[0] = &albanie;
	grece.frontieres[1] = &macedoine;
	grece.frontieres[2] = &bulgarie;
	grece.frontieres[3] = &turquie;
	all_zero(&guatemala);
	guatemala.noms[0] = "GUATEMALA";
	guatemala.frontieres[0] = &mexique;
	guatemala.frontieres[1] = &belize;
	guatemala.frontieres[2] = &honduras;
	guatemala.frontieres[3] = &salvador;
	all_zero(&guinee);
	guinee.noms[0] = "GUINEE";
	guinee.noms[1] = "GUINEE CONAKRY";
	guinee.frontieres[0] = &guinee_bissau;
	guinee.frontieres[1] = &senegal;
	guinee.frontieres[2] = &mali;
	guinee.frontieres[3] = &cote_ivoire;
	guinee.frontieres[4] = &liberia;
	guinee.frontieres[5]= &sierra_leone;
	all_zero(&guinee_equatoriale);
	guinee_equatoriale.noms[0] = "GUINEE EQUATORIALE";
	guinee_equatoriale.frontieres[0] = &cameroun;
	guinee_equatoriale.frontieres[1] = &gabon;
	all_zero(&guinee_bissau);
	guinee_bissau.noms[0] = "GUINEE BISSAU";
	guinee_bissau.frontieres[0] = &senegal;
	guinee_bissau.frontieres[1] = &guinee;
	all_zero(&guyana);
	guyana.noms[0] = "GUYANA";
	guyana.frontieres[0] = &venezuela;
	guyana.frontieres[1] = &bresil;
	guyana.frontieres[2] = &suriname;
	all_zero(&honduras);
	honduras.noms[0] = "HONDURAS";
	honduras.frontieres[0] = &guatemala;
	honduras.frontieres[1] = &salvador;
	honduras.frontieres[2] = &nicaragua;
	all_zero(&hongrie);
	hongrie.noms[0] = "HONGRIE";
	hongrie.frontieres[0] = &autriche;
	hongrie.frontieres[1] = &slovaquie;
	hongrie.frontieres[2] = &ukraine;
	hongrie.frontieres[3] = &roumanie;
	hongrie.frontieres[4] = &serbie;
	hongrie.frontieres[5] = &croatie;
	hongrie.frontieres[6] = &slovenie;
	all_zero(&inde);
	inde.noms[0] = "INDE";
	inde.frontieres[0] = &pakistan;
	inde.frontieres[1] = &chine;
	inde.frontieres[2] = &nepal;
	inde.frontieres[3] = &bhoutan;
	inde.frontieres[4] = &bangladesh;
	inde.frontieres[5] = &birmanie;
	all_zero(&indonesie);
	indonesie.noms[0] = "INDONESIE";
	indonesie.frontieres[0] = &malaisie;
	indonesie.frontieres[1] = &papouasie;
	all_zero(&irak);
	irak.noms[0] = "IRAK";
	irak.frontieres[0] = &jordanie;
	irak.frontieres[1] = &syrie;
	irak.frontieres[2] = &turquie;
	irak.frontieres[3] = &iran;
	irak.frontieres[4] = &koweit;
	irak.frontieres[5] = &arabie_saoudite;
	all_zero(&iran),
	iran.noms[0] = "IRAN";
	iran.frontieres[0] = &irak;
	iran.frontieres[1] = &turquie;
	iran.frontieres[2] = &armenie;
	iran.frontieres[3] = &azerbaidjan;
	iran.frontieres[4] = &turkmenistan;
	iran.frontieres[5] = &afghanistan;
	iran.frontieres[6] = &pakistan;
	all_zero(&palestine),
	palestine.noms[0] = "PALESTINE";
	palestine.frontieres[0] = &egypte;
	palestine.frontieres[1] = &liban;
	palestine.frontieres[2] = &syrie;
	palestine.frontieres[3] = &jordanie;
	all_zero(&italie);
	italie.noms[0] = "ITALIE";
	italie.frontieres[0] = &france;
	italie.frontieres[1] = &suisse;
	italie.frontieres[2] = &autriche;
	italie.frontieres[3] = &slovenie;
	all_zero(&jordanie);
	jordanie.noms[0] = "JORDANIE";
	jordanie.frontieres[0] = &palestine;
	jordanie.frontieres[1] = &syrie;
	jordanie.frontieres[2] = &irak;
	jordanie.frontieres[3] = &arabie_saoudite;
	all_zero(&kazakhstan);
	kazakhstan.noms[0] = "KAZAKHSTAN";
	kazakhstan.frontieres[0] = &russie;
	kazakhstan.frontieres[1] = &ouzbekistan;
	kazakhstan.frontieres[2] = &kirghizistan;
	kirghizistan.frontieres[3] = &chine;
	kazakhstan.frontieres[4] = &turkmenistan;
	all_zero(&kenya);
	kenya.noms[0] = "KENYA";
	kenya.frontieres[0] = &ouganda;
	kenya.frontieres[1] = &soudan_du_sud;
	kenya.frontieres[2] = &ethiopie;
	kenya.frontieres[3] = &somalie;
	kenya.frontieres[4] = &tanzanie;
	all_zero(&kirghizistan);
	kirghizistan.noms[0] = "KIRGHIZISTAN";
	kirghizistan.frontieres[0] = &tadjikistan;
	kirghizistan.frontieres[1] = &kazakhstan;
	kirghizistan.frontieres[2] = &chine;
	all_zero(&kosovo);
	kosovo.noms[0] = "KOSOVO";
	kosovo.frontieres[0] = &montenegro;
	kosovo.frontieres[1] = &serbie;
	kosovo.frontieres[2] = &macedoine;
	kosovo.frontieres[3] = &albanie;
	all_zero(&koweit);
	koweit.noms[0] = "KOWEIT";
	koweit.frontieres[0] = &arabie_saoudite;
	koweit.frontieres[1] = &irak;
	all_zero(&laos);
	laos.noms[0] = "LAOS";
	laos.frontieres[0] = &birmanie;
	laos.frontieres[1] = &chine;
	laos.frontieres[2] = &vietnam;
	laos.frontieres[3] = &cambodge;
	laos.frontieres[4] = &thailande;
	all_zero(&lesotho);
	lesotho.noms[0] = "LESOTHO";
	lesotho.frontieres[0] = &afrique_du_sud;
	all_zero(&lettonie);
	lettonie.noms[0] = "LETTONIE";
	lettonie.frontieres[0] = &estonie;
	lettonie.frontieres[1] = &russie;
	lettonie.frontieres[2] = &bielorussie;
	lettonie.frontieres[3] = &lituanie;
	all_zero(&liban);
	liban.noms[0] = "LIBAN";
	liban.frontieres[0] = &syrie;
	liban.frontieres[1] = &palestine;
	all_zero(&liberia);
	liberia.noms[0] = "LIBERIA";
	liberia.frontieres[0] = &sierra_leone;
	liberia.frontieres[1] = &guinee;
	liberia.frontieres[2] = &cote_ivoire;
	all_zero(&libye);
	libye.noms[0] = "LIBYE";
	libye.frontieres[0] = &tunisie;
	libye.frontieres[1] = &algerie;
	libye.frontieres[2] = &niger;
	libye.frontieres[3] = &tchad;
	libye.frontieres[4] = &soudan;
	libye.frontieres[5] = &egypte;
	all_zero(&liechtenstein);
	liechtenstein.noms[0] = "LIECHTENSTEIN";
	liechtenstein.frontieres[0] = &suisse;
	liechtenstein.frontieres[1] = &autriche;
	all_zero(&lituanie);
	lituanie.noms[0] = "LITUANIE";
	lituanie.frontieres[0] = &lettonie;
	lituanie.frontieres[1] = &bielorussie;
	lituanie.frontieres[2] = &pologne;
	all_zero(&luxembourg);
	luxembourg.noms[0] = "LUXEMBOURG";
	luxembourg.frontieres[0] = &france;
	luxembourg.frontieres[1] = &belgique;
	luxembourg.frontieres[2] = &allemagne;
	all_zero(&macedoine);
	macedoine.noms[0] = "MACEDOINE";
	macedoine.noms[1] = "MACEDOINE DU NORD";
	macedoine.frontieres[0] = &albanie;
	macedoine.frontieres[1] = &kosovo;
	macedoine.frontieres[2] = &serbie;
	macedoine.frontieres[3] = &bulgarie;
	macedoine.frontieres[4] = &grece;
	all_zero(&malaisie);
	malaisie.noms[0] = "MALAISIE";
	malaisie.frontieres[0] = &indonesie;
	malaisie.frontieres[1] = &brunei;
	malaisie.frontieres[2] = &thailande;
	malaisie.frontieres[3] = &singapour;
	all_zero(&malawi);
	malawi.noms[0] = "MALAWI";
	malawi.frontieres[0] = &zambie;
	malawi.frontieres[1] = &tanzanie;
	malawi.frontieres[2] = &mozambique;
	all_zero(&mali);
	mali.noms[0] = "MALI";
	mali.frontieres[0] = &mauritanie;
	mali.frontieres[1] = &algerie;
	mali.frontieres[2] = &niger;
	mali.frontieres[3] = &burkina_faso;
	mali.frontieres[4] = &cote_ivoire;
	mali.frontieres[5] = &guinee;
	mali.frontieres[6] = &senegal;
	all_zero(&maroc);
	maroc.noms[0] = "MAROC";
	maroc.frontieres[0] = &algerie;
	maroc.frontieres[1] = &mauritanie;
	all_zero(&mexique);
	mexique.noms[0] = "MEXIQUE";
	mexique.frontieres[0] = &etats_unis;
	mexique.frontieres[1] = &guatemala;
	mexique.frontieres[2] = &belize;
	all_zero(&mauritanie);
	mauritanie.noms[0] = "MAURITANIE";
	mauritanie.frontieres[0] = &maroc;
	mauritanie.frontieres[1] = &algerie;
	mauritanie.frontieres[2] = &mali;
	mauritanie.frontieres[3] = &senegal;
	all_zero(&moldavie);
	moldavie.noms[0] = "MOLDAVIE";
	moldavie.frontieres[0] = &roumanie;
	moldavie.frontieres[1] = &ukraine;
	all_zero(&monaco);
	monaco.noms[0] = "MONACO";
	monaco.frontieres[0] = &france;
	all_zero(&mongolie);
	mongolie.noms[0] = "MONGOLIE";
	mongolie.frontieres[0] = &russie;
	mongolie.frontieres[1] = &chine;
	all_zero(&montenegro);
	montenegro.noms[0] = "MONTENEGRO";
	montenegro.frontieres[0] = &croatie;
	montenegro.frontieres[1] = &bosnie;
	montenegro.frontieres[2] = &serbie;
	montenegro.frontieres[3] = &kosovo;
	montenegro.frontieres[4] = &albanie;
	all_zero(&mozambique);
	mozambique.noms[0] = "MOZAMBIQUE";
	mozambique.frontieres[0] = &tanzanie;
	mozambique.frontieres[1] = &malawi;
	mozambique.frontieres[2] = &zambie;
	mozambique.frontieres[3] = &zimbabwe;
	mozambique.frontieres[4] = &afrique_du_sud;
	mozambique.frontieres[5] = &eswatini;
	all_zero(&namibie);
	namibie.noms[0] = "NAMIBIE";
	namibie.frontieres[0] = &angola;
	namibie.frontieres[1] = &zambie;
	namibie.frontieres[2] = &botswana;
	namibie.frontieres[3] = &afrique_du_sud;
	all_zero(&nepal);
	nepal.noms[0] = "NEPAL";
	nepal.frontieres[0] = &chine;
	nepal.frontieres[1] = &inde;
	all_zero(&nicaragua);
	nicaragua.noms[0] = "NICARAGUA";
	nicaragua.frontieres[0] = &honduras;
	nicaragua.frontieres[1] = &costa_rica;
	all_zero(&niger);
	niger.noms[0] = "NIGER";
	niger.frontieres[0] = &mali;
	niger.frontieres[1] = &algerie;
	niger.frontieres[2] = &libye;
	niger.frontieres[3] = &tchad;
	niger.frontieres[4] = &nigeria;
	niger.frontieres[5] = &benin;
	niger.frontieres[6] = &burkina_faso;
	all_zero(&nigeria);
	nigeria.noms[0] = "NIGERIA";
	nigeria.frontieres[0] = &benin;
	nigeria.frontieres[1] = &niger;
	nigeria.frontieres[2] = &tchad;
	nigeria.frontieres[3] = &cameroun;
	all_zero(&norvege);
	norvege.noms[0] = "NORVEGE";
	norvege.frontieres[0] = &suede;
	norvege.frontieres[1] = &finlande;
	norvege.frontieres[2] = &russie;
	all_zero(&oman);
	oman.noms[0] = "OMAN";
	oman.frontieres[0] = &arabie_saoudite;
	oman.frontieres[1] = &yemen;
	oman.frontieres[2] = &emirats_arabes_unis;
	all_zero(&ouganda);
	ouganda.noms[0] = "OUGANDA";
	ouganda.frontieres[0] = &republique_democratique_du_congo;
	ouganda.frontieres[1] = &soudan_du_sud;
	ouganda.frontieres[2] = &kenya;
	ouganda.frontieres[3] = &tanzanie;
	ouganda.frontieres[4] = &rwanda;
	all_zero(&ouzbekistan);
	ouzbekistan.noms[0] = "OUZBEKISTAN";
	ouzbekistan.frontieres[0] = &kazakhstan;
	ouzbekistan.frontieres[1] = &turkmenistan;
	ouzbekistan.frontieres[2] = &afghanistan;
	ouzbekistan.frontieres[3] = &tadjikistan;
	ouzbekistan.frontieres[4] = &kirghizistan;
	all_zero(&pakistan);
	pakistan.noms[0] = "PAKISTAN";
	pakistan.frontieres[0] = &iran;
	pakistan.frontieres[1] = &afghanistan;
	pakistan.frontieres[2] = &chine;
	pakistan.frontieres[3] = &inde;
	all_zero(&panama);
	panama.noms[0] = "PANAMA";
	panama.frontieres[0] = &costa_rica;
	panama.frontieres[1] = &colombie;
	all_zero(&papouasie);
	papouasie.noms[0] = "PAPOUASIE NOUVELLE GUINEE";
	papouasie.noms[1] = "PAPOUASIE";
	papouasie.frontieres[0] = &indonesie;
	all_zero(&paraguay);
	paraguay.noms[0] = "PARAGUAY";
	paraguay.frontieres[0] = &bolivie;
	paraguay.frontieres[1] = &bresil;
	paraguay.frontieres[2] = &argentine;
	all_zero(&pays_bas);
	pays_bas.noms[0] = "PAYS BAS";
	pays_bas.frontieres[0] = &allemagne;
	pays_bas.frontieres[1] = &belgique;
	all_zero(&perou);
	perou.noms[0] = "PEROU";
	perou.frontieres[0] = &equateur;
	perou.frontieres[1] = &colombie;
	perou.frontieres[2] = &bresil;
	perou.frontieres[3] = &bolivie;
	perou.frontieres[4] = &chili;
	all_zero(&pologne);
	pologne.noms[0] = "POLOGNE";
	pologne.frontieres[0] = &allemagne;
	pologne.frontieres[1] = &tchequie;
	pologne.frontieres[2] = &slovaquie;
	pologne.frontieres[3] = &ukraine;
	pologne.frontieres[4] = &bielorussie;
	pologne.frontieres[5] = &lituanie;
	all_zero(&portugal);
	portugal.noms[0] = "PORTUGAL";
	portugal.frontieres[0] = &espagne;
	all_zero(&qatar);
	qatar.noms[0] = "QATAR";
	qatar.frontieres[0] = &arabie_saoudite;
	all_zero(&republique_centrafrique);
	republique_centrafrique.noms[0] = "REPUBLIQUE CENTRAFRICAINE";
	republique_centrafrique.noms[1] = "CENTRAFRIQUE";
	republique_centrafrique.frontieres[0] = &cameroun;
	republique_centrafrique.frontieres[1] = &tchad;
	republique_centrafrique.frontieres[2] = &soudan;
	republique_centrafrique.frontieres[3] = &soudan_du_sud;
	republique_centrafrique.frontieres[4] = &republique_democratique_du_congo;
	republique_centrafrique.frontieres[5] = &republique_du_congo;
	all_zero(&republique_democratique_du_congo);
	republique_democratique_du_congo.noms[0] = "REPUBLIQUE DEMOCRATIQUE DU CONGO";
	republique_democratique_du_congo.noms[1] = "CONGO KINSHASA";
	republique_democratique_du_congo.frontieres[0] = &republique_du_congo;
	republique_democratique_du_congo.frontieres[1] = &republique_centrafrique;
	republique_democratique_du_congo.frontieres[2] = &soudan_du_sud;
	republique_democratique_du_congo.frontieres[3] = &ouganda;
	republique_democratique_du_congo.frontieres[4] = &rwanda;
	republique_democratique_du_congo.frontieres[5] = &burundi;
	republique_democratique_du_congo.frontieres[6] = &tanzanie;
	republique_democratique_du_congo.frontieres[7] = &zambie;
	republique_democratique_du_congo.frontieres[8] = &angola;
	all_zero(&tchequie);
	tchequie.noms[0] = "TCHEQUIE";
	tchequie.noms[1] = "REPUBLIQUE TCHEQUE";
	tchequie.frontieres[0] = &allemagne;
	tchequie.frontieres[1] = &pologne;
	tchequie.frontieres[2] = &slovaquie;
	tchequie.frontieres[3] = &autriche;
	all_zero(&roumanie);
	roumanie.noms[0] = "ROUMANIE";
	roumanie.frontieres[0] = &hongrie;
	roumanie.frontieres[1] = &ukraine;
	roumanie.frontieres[2] = &moldavie;
	roumanie.frontieres[3] = &bulgarie;
	roumanie.frontieres[4] = &serbie;
	all_zero(&russie);
	russie.noms[0] = "RUSSIE";
	russie.frontieres[0] = &norvege;
	russie.frontieres[1] = &finlande;
	russie.frontieres[2] = &estonie;
	russie.frontieres[3] = &lettonie;
	russie.frontieres[4] = &bielorussie;
	russie.frontieres[5] = &ukraine;
	russie.frontieres[6] = &georgie;
	russie.frontieres[7] = &azerbaidjan;
	russie.frontieres[8] = &kazakhstan;
	russie.frontieres[9] = &chine;
	russie.frontieres[10] = &mongolie;
	russie.frontieres[11] = &coree_du_nord;
	all_zero(&rwanda);
	rwanda.noms[0] = "RWANDA";
	rwanda.frontieres[0] = &republique_democratique_du_congo;
	rwanda.frontieres[1] = &ouganda;
	rwanda.frontieres[2] = &tanzanie;
	rwanda.frontieres[3] = &burundi;
	all_zero(&saint_marin);
	saint_marin.noms[0] = "SAINT MARIN";
	saint_marin.frontieres[0] = &italie;
	all_zero(&salvador);
	salvador.noms[0] = "SALVADOR";
	salvador.noms[1] = "EL SALVADOR";
	salvador.frontieres[0] = &guatemala;
	salvador.frontieres[1] = &honduras;
	all_zero(&senegal);
	senegal.noms[0] = "SENEGAL";
	senegal.frontieres[0] = &gambie;
	senegal.frontieres[1] = &mauritanie;
	senegal.frontieres[2] = &mali;
	senegal.frontieres[3] = &guinee;
	senegal.frontieres[4] = &guinee_bissau;
	all_zero(&serbie);
	serbie.noms[0] = "SERBIE";
	serbie.frontieres[0] = &croatie;
	serbie.frontieres[1] = &hongrie;
	serbie.frontieres[2] = &roumanie;
	serbie.frontieres[3] = &bulgarie;
	serbie.frontieres[4] = &macedoine;
	serbie.frontieres[5] = &kosovo;
	serbie.frontieres[6] = &montenegro;
	serbie.frontieres[7] = &bosnie;
	all_zero(&sierra_leone);
	sierra_leone.noms[0] = "SIERRA LEONE";
	sierra_leone.frontieres[0] = &guinee;
	sierra_leone.frontieres[1] = &liberia;
	all_zero(&singapour);
	singapour.noms[0] = "SINGAPOUR";
	singapour.frontieres[0] = &malaisie;
	all_zero(&slovaquie);
	slovaquie.noms[0] = "SLOVAQUIE";
	slovaquie.frontieres[0] = &autriche;
	slovaquie.frontieres[1] = &tchequie;
	slovaquie.frontieres[2] = &pologne;
	slovaquie.frontieres[3] = &ukraine;
	slovaquie.frontieres[4] = &hongrie;
	all_zero(&slovenie);
	slovenie.noms[0] = "SLOVENIE";
	slovenie.frontieres[0] = &italie;
	slovenie.frontieres[1] = &autriche;
	slovenie.frontieres[2] = &hongrie;
	slovenie.frontieres[3] = &croatie;
	all_zero(&somalie);
	somalie.noms[0] = "SOMALIE";
	somalie.frontieres[0] = &djibouti;
	somalie.frontieres[1] = &ethiopie;
	somalie.frontieres[2] = &kenya;
	all_zero(&soudan);
	soudan.noms[0] = "SOUDAN";
	soudan.frontieres[0] = &egypte;
	soudan.frontieres[1] = &libye;
	soudan.frontieres[2] = &tchad;
	soudan.frontieres[3] = &republique_centrafrique;
	soudan.frontieres[4] = &soudan_du_sud;
	soudan.frontieres[5] = &ethiopie;
	soudan.frontieres[6] = &erythree;
	all_zero(&soudan_du_sud);
	soudan_du_sud.noms[0] = "SOUDAN DU SUD";
	soudan_du_sud.frontieres[0] = &soudan;
	soudan_du_sud.frontieres[1] = &republique_centrafrique;
	soudan_du_sud.frontieres[2] = &republique_democratique_du_congo;
	soudan_du_sud.frontieres[3] = &ouganda;
	soudan_du_sud.frontieres[4] = &kenya;
	soudan_du_sud.frontieres[5] = &ethiopie;
	all_zero(&suede);
	suede.noms[0] = "SUEDE";
	suede.frontieres[0] = &norvege;
	suede.frontieres[1] = &danemark;
	suede.frontieres[2] = &finlande;
	all_zero(&suisse);
	suisse.noms[0] = "SUISSE";
	suisse.frontieres[0] = &france;
	suisse.frontieres[1] = &allemagne;
	suisse.frontieres[2] = &liechtenstein;
	suisse.frontieres[3] = &autriche;
	suisse.frontieres[4] = &italie;
	all_zero(&suriname);
	suriname.noms[0] = "SURINAME";
	suriname.frontieres[0] = &guyana;
	suriname.frontieres[1] = &france;
	suriname.frontieres[2] = &bresil;
	all_zero(&syrie);
	syrie.noms[0] = "SYRIE";
	syrie.frontieres[0] = &turquie;
	syrie.frontieres[1] = &liban;
	syrie.frontieres[2] = &palestine;
	syrie.frontieres[3] = &jordanie;
	syrie.frontieres[4] = &irak;
	all_zero(&tadjikistan);
	tadjikistan.noms[0] = "TADJIKISTAN";
	tadjikistan.frontieres[0] = &ouzbekistan;
	tadjikistan.frontieres[1] = &afghanistan;
	tadjikistan.frontieres[2] = &chine;
	tadjikistan.frontieres[3] = &kirghizistan;
	all_zero(&tanzanie);
	tanzanie.noms[0] = "TANZANIE";
	tanzanie.frontieres[0] = &kenya;
	tanzanie.frontieres[1] = &ouganda;
	tanzanie.frontieres[2] = &rwanda;
	tanzanie.frontieres[3] = &burundi;
	tanzanie.frontieres[4] = &republique_democratique_du_congo;
	tanzanie.frontieres[5] = &zambie;
	tanzanie.frontieres[6] = &malawi;
	tanzanie.frontieres[7] = &mozambique;
	all_zero(&tchad);
	tchad.noms[0] = "TCHAD";
	tchad.frontieres[0] = &libye;
	tchad.frontieres[1] = &niger;
	tchad.frontieres[2] = &cameroun;
	tchad.frontieres[3] = &republique_centrafrique;
	tchad.frontieres[4] = &soudan;
	all_zero(&thailande);
	thailande.noms[0] = "THAILANDE";
	thailande.frontieres[0] = &birmanie;
	thailande.frontieres[1] = &laos;
	thailande.frontieres[2] = &cambodge;
	thailande.frontieres[3] = &malaisie;
	all_zero(&togo);
	togo.noms[0] = "TOGO";
	togo.frontieres[0] = &ghana;
	togo.frontieres[1] = &burkina_faso;
	togo.frontieres[2] = &benin;
	all_zero(&tunisie);
	tunisie.noms[0] = "TUNISIE";
	tunisie.frontieres[0] = &algerie;
	tunisie.frontieres[1] = &libye;
	all_zero(&turkmenistan);
	turkmenistan.noms[0] = "TURKMENISTAN";
	turkmenistan.frontieres[0] = &kazakhstan;
	turkmenistan.frontieres[1] = &ouzbekistan;
	turkmenistan.frontieres[2] = &afghanistan;
	turkmenistan.frontieres[3] = &iran;
	all_zero(&turquie);
	turquie.noms[0]= "TURQUIE";
	turquie.frontieres[0] = &grece;
	turquie.frontieres[1] = &georgie;
	turquie.frontieres[2] = &armenie;
	turquie.frontieres[3] = &iran;
	turquie.frontieres[4] = &irak;
	turquie.frontieres[5] = &syrie;
	turquie.frontieres[6] = &bulgarie;
	all_zero(&ukraine);
	ukraine.noms[0] = "UKRAINE";
	ukraine.frontieres[0] = &pologne;
	ukraine.frontieres[1] = &bielorussie;
	ukraine.frontieres[2] = &russie;
	ukraine.frontieres[3] = &moldavie;
	ukraine.frontieres[4] = &roumanie;
	ukraine.frontieres[5] = &hongrie;
	ukraine.frontieres[6] = &slovaquie;
	all_zero(&uruguay);
	uruguay.noms[0] = "URUGUAY";
	uruguay.frontieres[0] = &argentine;
	uruguay.frontieres[1] = &bresil;
	all_zero(&vatican);
	vatican.noms[0] = "VATICAN";
	vatican.frontieres[0] = &italie;
	all_zero(&venezuela);
	venezuela.noms[0] = "VENEZUELA";
	venezuela.frontieres[0] = &colombie;
	venezuela.frontieres[1] = &guyana;
	venezuela.frontieres[2] = &bresil;
	all_zero(&vietnam);
	vietnam.noms[0] = "VIETNAM";
	vietnam.frontieres[0] = &chine;
	vietnam.frontieres[1] = &laos;
	vietnam.frontieres[2] = &cambodge;
	all_zero(&yemen);
	yemen.noms[0] = "YEMEN";
	yemen.frontieres[0] = &arabie_saoudite;
	yemen.frontieres[1] = &oman;
	all_zero(&zambie);
	zambie.noms[0] = "ZAMBIE";
	zambie.frontieres[0] = &angola;
	zambie.frontieres[1] = &republique_democratique_du_congo;
	zambie.frontieres[2] = &tanzanie;
	zambie.frontieres[3] = &malawi;
	zambie.frontieres[4] = &mozambique;
	zambie.frontieres[5] = &zimbabwe;
	zambie.frontieres[6] = &botswana;
	zambie.frontieres[7] = &namibie;
	all_zero(&zimbabwe);
	zimbabwe.noms[0] = "ZIMBABWE";
	zimbabwe.frontieres[0] = &zambie;
	zimbabwe.frontieres[1] = &mozambique;
	zimbabwe.frontieres[2] = &afrique_du_sud;
	zimbabwe.frontieres[3] = &botswana;
}
